package com.multipong.server;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'patriknygren' at '2016-11-27 14:45' with Gradle 2.13
 *
 * @author patriknygren, @date 2016-11-27 14:45
 */
public class Test {

}
