package com.multipong;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'patriknygren' at '2016-11-24 21:05' with Gradle 2.11
 *
 * @author patriknygren, @date 2016-11-24 21:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
