package com.multipong;

import org.junit.Test;

import com.multipong.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'patriknygren' at '2016-11-24 21:05' with Gradle 2.11
 *
 * @author patriknygren, @date 2016-11-24 21:05
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
